service: express-api

provider:
  name: aws
  runtime: nodejs18.x
  region: us-east-1
  stage: dev

plugins:
  - serverless-offline

functions:
  app:
    handler: src/index.handler  # adjust path to your file
    events:
      - http:
          path: /{proxy+}
          method: any
